### ISSUE TITLE
Q: What is the reason to have 3 tables for users

### ISSUE THREAD

**Issue by mynkow** [joshuadeanhall/AspNet.Identity.Cassandra#10]
Hey,

What is the reason to have 3 tables for users:
- users
- users_by_username
- users_by_email

Isn't possible to have one table with `username` and `email` as cluster keys?

**Comment by LukeTillman** [comment]
Let's take a look at what that table might look like:

```
CREATE TABLE users_test (
  userid uuid,
  username text,
  email text,
  ... rest of columns ...
  PRIMARY KEY (userid, username, email)
);
```

This is a single users table with userid as partition key and username and email as the clustering keys. Now if you were to try and lookup a user by email address:

```
SELECT * FROM users_test WHERE email = 'some@email.com'
```

Cassandra would throw an error at you telling you that it needs a value for the partition key `userid` and clustering column `username`. That's because Cassandra only allows queries that will be efficient in a distributed database. 

Let's think about what Cassandra would have to do to answer this query (if it actually allowed it). Since the partition key (`userid`) is used to distribute data around the ring and we didn't provide a value for it in our query (basically we didn't tell Cassandra on what node to go find the data), it would have to query _every node in the cluster_ and ask if it had data matching that email address. That would be terrible for performance (particularly as the number of nodes in our cluster goes up) and also bad for high availability (because a small number of nodes being down would make it impossible to run the query that asks every node in the cluster the question).

So, as a result, we tend to denormalize data in Cassandra when we data model and build tables based on the queries we're going to run. I've got some slides on [basic data modeling](http://www.slideshare.net/LukeTillman/introduction-to-data-modeling-with-apache-cassandra-45910030) and [DataStax Academy](https://academy.datastax.com/courses) has some good free courses if you're interested in digging in more. Hope that helps explain things a bit.

**Comment by mynkow** [comment]
Hi, thank you for the detailed explanation.

I have just one follow up question. What if we use index for username and email?

**Comment by LukeTillman** [comment]
Good question. Secondary indexes in Cassandra don't work quite the same way as indexes in a RDBMS. For more details on the problems with them on high cardinality columns (like email address and username are), see the [DataStax docs on when to use an index](https://docs.datastax.com/en/cql/3.1/cql/ddl/ddl_when_use_index_c.html). Also, since indexes are maintained on a per-table, per-node basis (i.e. a node would only store an index of our `users_test` table for the data that's lives on that node), we'd still have the same problem I described above.

Since we'd be doing a query and not providing a value for our partition key (`userid`), Cassandra would have to go and ask every node in the cluster if they had the data. Even with a secondary index on those columns. So we'd essentially be doing a "full cluster scan" every time. And that's bad for the reasons I mentioned above.

Hope that helps.

**Comment by mynkow** [comment]
Thank you for your time explaining this to me. Have a nice day.
